### ISSUE TITLE
Backend - Build APIs

### ISSUE THREAD

**Issue by Jalzu1007** [andreaber23/myhealthspace#17]
- Create GraphQL queries and mutations for user management etc.
- Building cardio and resistance CRUD.
-  Connecting to Frontend.

**Comment by calzu0821** [comment]
- Create GraphQL queries and mutations for creating/retrieving, adding, updating, and deleting workout data.

- Implement the logic to perform these operations in your resolvers.

**Comment by Jalzu1007** [comment]
Completed!
